(AST_FUNC ((int 2) func)
          (AST_DECL (= (int a) (+ 1 (* 2 3))))
          (AST_RETURN (* (int a) 10)))
(AST_FUNC ((int 2) main)
          (AST_DECL (= (int i) 0))
          (AST_DECL (= (float i1) 0))
          (AST_DECL (= (char i2) 0))
          (AST_DECL (= (double i3) 0))
          (AST_DECL (= (int sum) 0))
          (AST_IF (COND (int sum))
                  (THEN (AST_FUNCALL func))
                  (ELSE (+ (* 10 (AST_FUNCALL func)) 10)
                        (AST_FUNCALL func)))
          (AST_WHILE (COND (int i))
                     (BODY (= (int i) (+ (int i) 1))
                           (AST_FUNCALL func)))
          (AST_FOR (INIT (= (int i) 100))
                   (COND (int i))
                   (STEP (= (int i) (- (int i) 1)))
                   (BODY (= (int sum) (+ (int sum) (int i)))))
          (AST_RETURN (int sum))) 